
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class CardTemplate : Luban.BeanBase
{
    public CardTemplate(ByteBuf _buf) 
    {
        CardName = _buf.ReadString();
        Desc = _buf.ReadString();
        Color = _buf.ReadString();
    }

    public static CardTemplate DeserializeCardTemplate(ByteBuf _buf)
    {
        return new CardTemplate(_buf);
    }

    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string CardName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 颜色标记
    /// </summary>
    public readonly string Color;
   
    public const int __ID__ = -693440566;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cardName:" + CardName + ","
        + "desc:" + Desc + ","
        + "color:" + Color + ","
        + "}";
    }
}
}

