
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class DinerTemplate : Luban.BeanBase
{
    public DinerTemplate(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
    }

    public static DinerTemplate DeserializeDinerTemplate(ByteBuf _buf)
    {
        return new DinerTemplate(_buf);
    }

    /// <summary>
    /// 模板名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -1720214160;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "}";
    }
}
}

