
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 食客池条目
/// </summary>
public sealed partial class DinerPoolEntry : Luban.BeanBase
{
    public DinerPoolEntry(ByteBuf _buf) 
    {
        TemplateId = _buf.ReadInt();
        Count = _buf.ReadInt();
        Weight = _buf.ReadInt();
    }

    public static DinerPoolEntry DeserializeDinerPoolEntry(ByteBuf _buf)
    {
        return new DinerPoolEntry(_buf);
    }

    /// <summary>
    /// 模板ID
    /// </summary>
    public readonly int TemplateId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -1274052736;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "templateId:" + TemplateId + ","
        + "count:" + Count + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

