
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EEmotionType
    {
        /// <summary>
        /// 轻松
        /// </summary>
        Relaxed = 1,
        /// <summary>
        /// 紧张
        /// </summary>
        Tense = 2,
        /// <summary>
        /// 惶恐
        /// </summary>
        Alarmed = 3,
        /// <summary>
        /// 恐惧
        /// </summary>
        Fear = 4,
    }

} 

