
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EEmotionPathId
    {
        /// <summary>
        /// 豪爽型
        /// </summary>
        Generous = 1,
        /// <summary>
        /// 紧张型
        /// </summary>
        Nervous = 2,
        /// <summary>
        /// 伪装型
        /// </summary>
        Disguise = 3,
        /// <summary>
        /// 平稳型
        /// </summary>
        Steady = 4,
    }

} 

