
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EFacilityScope
    {
        /// <summary>
        /// 座位
        /// </summary>
        Seat = 1,
        /// <summary>
        /// 区域
        /// </summary>
        Zone = 2,
        /// <summary>
        /// 全局
        /// </summary>
        Global = 3,
    }

} 

