
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 情绪阶梯步骤
/// </summary>
public sealed partial class EmotionStep : Luban.BeanBase
{
    public EmotionStep(ByteBuf _buf) 
    {
        Threshold = _buf.ReadFloat();
        EmotionType = (EEmotionType)_buf.ReadInt();
    }

    public static EmotionStep DeserializeEmotionStep(ByteBuf _buf)
    {
        return new EmotionStep(_buf);
    }

    /// <summary>
    /// 消费比例阈值
    /// </summary>
    public readonly float Threshold;
    /// <summary>
    /// 情绪类型
    /// </summary>
    public readonly EEmotionType EmotionType;
   
    public const int __ID__ = -156525145;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "threshold:" + Threshold + ","
        + "emotionType:" + EmotionType + ","
        + "}";
    }
}
}

