
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class EmotionPath : Luban.BeanBase
{
    public EmotionPath(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
    }

    public static EmotionPath DeserializeEmotionPath(ByteBuf _buf)
    {
        return new EmotionPath(_buf);
    }

    /// <summary>
    /// 路径名称
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -156632320;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "}";
    }
}
}

