
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ERace
    {
        /// <summary>
        /// 史莱姆
        /// </summary>
        Slime = 1,
        /// <summary>
        /// 哥布林
        /// </summary>
        Goblin = 2,
        /// <summary>
        /// 深海族
        /// </summary>
        Abyssal = 3,
        /// <summary>
        /// 蘑菇族
        /// </summary>
        Mushroom = 4,
        /// <summary>
        /// 骷髅族
        /// </summary>
        Skeleton = 5,
        /// <summary>
        /// 幽灵族
        /// </summary>
        Ghost = 6,
        /// <summary>
        /// 兽人族
        /// </summary>
        Orc = 7,
        /// <summary>
        /// 恶魔族
        /// </summary>
        Demon = 8,
    }

} 

