
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ERelicRarity
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 1,
        /// <summary>
        /// 非凡
        /// </summary>
        Uncommon = 2,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 3,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 4,
    }

} 

