
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EShopCategory
    {
        /// <summary>
        /// 座位
        /// </summary>
        Seat = 1,
        /// <summary>
        /// 设施
        /// </summary>
        Facility = 2,
        /// <summary>
        /// 遗物
        /// </summary>
        Relic = 3,
        /// <summary>
        /// 卖卡
        /// </summary>
        CardSell = 4,
    }

} 

