
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ETraitCategory
    {
        /// <summary>
        /// 吞噬
        /// </summary>
        Devour = 1,
        /// <summary>
        /// 加菜
        /// </summary>
        AddOn = 2,
        /// <summary>
        /// 环境
        /// </summary>
        Environment = 3,
    }

} 

