
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FlavorToFaceValue : Luban.BeanBase
{
    public FlavorToFaceValue(ByteBuf _buf) 
    {
    }

    public static FlavorToFaceValue DeserializeFlavorToFaceValue(ByteBuf _buf)
    {
        return new FlavorToFaceValue(_buf);
    }

   
    public const int __ID__ = 209520443;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

