
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GlobalConst : Luban.BeanBase
{
    public GlobalConst(ByteBuf _buf) 
    {
        DisguiseMultiplier = _buf.ReadFloat();
    }

    public static GlobalConst DeserializeGlobalConst(ByteBuf _buf)
    {
        return new GlobalConst(_buf);
    }

    /// <summary>
    /// 伪装型方差倍率
    /// </summary>
    public readonly float DisguiseMultiplier;
   
    public const int __ID__ = 800373088;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "disguiseMultiplier:" + DisguiseMultiplier + ","
        + "}";
    }
}
}

