
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 通用修正条目
/// </summary>
public sealed partial class ModifierEntry : Luban.BeanBase
{
    public ModifierEntry(ByteBuf _buf) 
    {
        Dimension = _buf.ReadString();
        Value = _buf.ReadFloat();
    }

    public static ModifierEntry DeserializeModifierEntry(ByteBuf _buf)
    {
        return new ModifierEntry(_buf);
    }

    /// <summary>
    /// 修改维度名
    /// </summary>
    public readonly string Dimension;
    /// <summary>
    /// 修改值
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = -1025346629;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "dimension:" + Dimension + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

