
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RestaurantProgress : Luban.BeanBase
{
    public RestaurantProgress(ByteBuf _buf) 
    {
    }

    public static RestaurantProgress DeserializeRestaurantProgress(ByteBuf _buf)
    {
        return new RestaurantProgress(_buf);
    }

   
    public const int __ID__ = 857776298;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

