
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ShopConfig : Luban.BeanBase
{
    public ShopConfig(ByteBuf _buf) 
    {
        BaseShopDisplay = _buf.ReadInt();
    }

    public static ShopConfig DeserializeShopConfig(ByteBuf _buf)
    {
        return new ShopConfig(_buf);
    }

    /// <summary>
    /// 商店基础展示数
    /// </summary>
    public readonly int BaseShopDisplay;
   
    public const int __ID__ = 396203512;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "baseShopDisplay:" + BaseShopDisplay + ","
        + "}";
    }
}
}

