
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class StartingCardConfig : Luban.BeanBase
{
    public StartingCardConfig(ByteBuf _buf) 
    {
    }

    public static StartingCardConfig DeserializeStartingCardConfig(ByteBuf _buf)
    {
        return new StartingCardConfig(_buf);
    }

   
    public const int __ID__ = -1462401294;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

