
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 起始手牌条目
/// </summary>
public sealed partial class StartingCardEntry : Luban.BeanBase
{
    public StartingCardEntry(ByteBuf _buf) 
    {
        Race = (ERace)_buf.ReadInt();
        FaceValue = _buf.ReadInt();
        Durability = _buf.ReadInt();
        Count = _buf.ReadInt();
    }

    public static StartingCardEntry DeserializeStartingCardEntry(ByteBuf _buf)
    {
        return new StartingCardEntry(_buf);
    }

    /// <summary>
    /// 种族
    /// </summary>
    public readonly ERace Race;
    /// <summary>
    /// 面值
    /// </summary>
    public readonly int FaceValue;
    /// <summary>
    /// 耐久
    /// </summary>
    public readonly int Durability;
    /// <summary>
    /// 张数
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -460992830;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "race:" + Race + ","
        + "faceValue:" + FaceValue + ","
        + "durability:" + Durability + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

