
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// 全局常量（单例）
    /// </summary>
    private TbGlobalConst m_TbGlobalConst;
    public TbGlobalConst TbGlobalConst 
    {
        get
        {
            if (m_TbGlobalConst == null)
            {
                m_TbGlobalConst = new TbGlobalConst(defaultLoader("tbglobalconst"));
                m_TbGlobalConst.ResolveRef(this);
            }
            return m_TbGlobalConst;
        }
        set
        {
            m_TbGlobalConst = value;
            m_TbGlobalConst.ResolveRef(this);
        }
    }
    /// <summary>
    /// 商店配置（单例）
    /// </summary>
    private TbShopConfig m_TbShopConfig;
    public TbShopConfig TbShopConfig 
    {
        get
        {
            if (m_TbShopConfig == null)
            {
                m_TbShopConfig = new TbShopConfig(defaultLoader("tbshopconfig"));
                m_TbShopConfig.ResolveRef(this);
            }
            return m_TbShopConfig;
        }
        set
        {
            m_TbShopConfig = value;
            m_TbShopConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 起始手牌配置（单例）
    /// </summary>
    private TbStartingCardConfig m_TbStartingCardConfig;
    public TbStartingCardConfig TbStartingCardConfig 
    {
        get
        {
            if (m_TbStartingCardConfig == null)
            {
                m_TbStartingCardConfig = new TbStartingCardConfig(defaultLoader("tbstartingcardconfig"));
                m_TbStartingCardConfig.ResolveRef(this);
            }
            return m_TbStartingCardConfig;
        }
        set
        {
            m_TbStartingCardConfig = value;
            m_TbStartingCardConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// Boss模板
    /// </summary>
    private TbBossTemplate m_TbBossTemplate;
    public TbBossTemplate TbBossTemplate 
    {
        get
        {
            if (m_TbBossTemplate == null)
            {
                m_TbBossTemplate = new TbBossTemplate(defaultLoader("tbbosstemplate"));
                m_TbBossTemplate.ResolveRef(this);
            }
            return m_TbBossTemplate;
        }
        set
        {
            m_TbBossTemplate = value;
            m_TbBossTemplate.ResolveRef(this);
        }
    }
    /// <summary>
    /// 卡牌卖出价格
    /// </summary>
    private TbCardSellPrice m_TbCardSellPrice;
    public TbCardSellPrice TbCardSellPrice 
    {
        get
        {
            if (m_TbCardSellPrice == null)
            {
                m_TbCardSellPrice = new TbCardSellPrice(defaultLoader("tbcardsellprice"));
                m_TbCardSellPrice.ResolveRef(this);
            }
            return m_TbCardSellPrice;
        }
        set
        {
            m_TbCardSellPrice = value;
            m_TbCardSellPrice.ResolveRef(this);
        }
    }
    /// <summary>
    /// 卡牌显示模板
    /// </summary>
    private TbCardTemplate m_TbCardTemplate;
    public TbCardTemplate TbCardTemplate 
    {
        get
        {
            if (m_TbCardTemplate == null)
            {
                m_TbCardTemplate = new TbCardTemplate(defaultLoader("tbcardtemplate"));
                m_TbCardTemplate.ResolveRef(this);
            }
            return m_TbCardTemplate;
        }
        set
        {
            m_TbCardTemplate = value;
            m_TbCardTemplate.ResolveRef(this);
        }
    }
    /// <summary>
    /// 食客池
    /// </summary>
    private TbDinerPool m_TbDinerPool;
    public TbDinerPool TbDinerPool 
    {
        get
        {
            if (m_TbDinerPool == null)
            {
                m_TbDinerPool = new TbDinerPool(defaultLoader("tbdinerpool"));
                m_TbDinerPool.ResolveRef(this);
            }
            return m_TbDinerPool;
        }
        set
        {
            m_TbDinerPool = value;
            m_TbDinerPool.ResolveRef(this);
        }
    }
    /// <summary>
    /// 食客模板
    /// </summary>
    private TbDinerTemplate m_TbDinerTemplate;
    public TbDinerTemplate TbDinerTemplate 
    {
        get
        {
            if (m_TbDinerTemplate == null)
            {
                m_TbDinerTemplate = new TbDinerTemplate(defaultLoader("tbdinertemplate"));
                m_TbDinerTemplate.ResolveRef(this);
            }
            return m_TbDinerTemplate;
        }
        set
        {
            m_TbDinerTemplate = value;
            m_TbDinerTemplate.ResolveRef(this);
        }
    }
    /// <summary>
    /// 情绪路径
    /// </summary>
    private TbEmotionPath m_TbEmotionPath;
    public TbEmotionPath TbEmotionPath 
    {
        get
        {
            if (m_TbEmotionPath == null)
            {
                m_TbEmotionPath = new TbEmotionPath(defaultLoader("tbemotionpath"));
                m_TbEmotionPath.ResolveRef(this);
            }
            return m_TbEmotionPath;
        }
        set
        {
            m_TbEmotionPath = value;
            m_TbEmotionPath.ResolveRef(this);
        }
    }
    /// <summary>
    /// 设施定义
    /// </summary>
    private TbFacility m_TbFacility;
    public TbFacility TbFacility 
    {
        get
        {
            if (m_TbFacility == null)
            {
                m_TbFacility = new TbFacility(defaultLoader("tbfacility"));
                m_TbFacility.ResolveRef(this);
            }
            return m_TbFacility;
        }
        set
        {
            m_TbFacility = value;
            m_TbFacility.ResolveRef(this);
        }
    }
    /// <summary>
    /// 口味到面值映射表
    /// </summary>
    private TbFlavorToFaceValue m_TbFlavorToFaceValue;
    public TbFlavorToFaceValue TbFlavorToFaceValue 
    {
        get
        {
            if (m_TbFlavorToFaceValue == null)
            {
                m_TbFlavorToFaceValue = new TbFlavorToFaceValue(defaultLoader("tbflavortofacevalue"));
                m_TbFlavorToFaceValue.ResolveRef(this);
            }
            return m_TbFlavorToFaceValue;
        }
        set
        {
            m_TbFlavorToFaceValue = value;
            m_TbFlavorToFaceValue.ResolveRef(this);
        }
    }
    /// <summary>
    /// 种族定义表
    /// </summary>
    private TbRace m_TbRace;
    public TbRace TbRace 
    {
        get
        {
            if (m_TbRace == null)
            {
                m_TbRace = new TbRace(defaultLoader("tbrace"));
                m_TbRace.ResolveRef(this);
            }
            return m_TbRace;
        }
        set
        {
            m_TbRace = value;
            m_TbRace.ResolveRef(this);
        }
    }
    /// <summary>
    /// 遗物定义(预留)
    /// </summary>
    private TbRelic m_TbRelic;
    public TbRelic TbRelic 
    {
        get
        {
            if (m_TbRelic == null)
            {
                m_TbRelic = new TbRelic(defaultLoader("tbrelic"));
                m_TbRelic.ResolveRef(this);
            }
            return m_TbRelic;
        }
        set
        {
            m_TbRelic = value;
            m_TbRelic.ResolveRef(this);
        }
    }
    /// <summary>
    /// 餐厅进度配置
    /// </summary>
    private TbRestaurantProgress m_TbRestaurantProgress;
    public TbRestaurantProgress TbRestaurantProgress 
    {
        get
        {
            if (m_TbRestaurantProgress == null)
            {
                m_TbRestaurantProgress = new TbRestaurantProgress(defaultLoader("tbrestaurantprogress"));
                m_TbRestaurantProgress.ResolveRef(this);
            }
            return m_TbRestaurantProgress;
        }
        set
        {
            m_TbRestaurantProgress = value;
            m_TbRestaurantProgress.ResolveRef(this);
        }
    }
    /// <summary>
    /// 座位类型
    /// </summary>
    private TbSeatType m_TbSeatType;
    public TbSeatType TbSeatType 
    {
        get
        {
            if (m_TbSeatType == null)
            {
                m_TbSeatType = new TbSeatType(defaultLoader("tbseattype"));
                m_TbSeatType.ResolveRef(this);
            }
            return m_TbSeatType;
        }
        set
        {
            m_TbSeatType = value;
            m_TbSeatType.ResolveRef(this);
        }
    }
    /// <summary>
    /// 每日关卡配置
    /// </summary>
    private TbStage m_TbStage;
    public TbStage TbStage 
    {
        get
        {
            if (m_TbStage == null)
            {
                m_TbStage = new TbStage(defaultLoader("tbstage"));
                m_TbStage.ResolveRef(this);
            }
            return m_TbStage;
        }
        set
        {
            m_TbStage = value;
            m_TbStage.ResolveRef(this);
        }
    }
    /// <summary>
    /// 食客特质
    /// </summary>
    private TbTrait m_TbTrait;
    public TbTrait TbTrait 
    {
        get
        {
            if (m_TbTrait == null)
            {
                m_TbTrait = new TbTrait(defaultLoader("tbtrait"));
                m_TbTrait.ResolveRef(this);
            }
            return m_TbTrait;
        }
        set
        {
            m_TbTrait = value;
            m_TbTrait.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
