
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// Boss模板
/// </summary>
public partial class TbBossTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, BossTemplate> _dataMap;
    private readonly System.Collections.Generic.List<BossTemplate> _dataList;
    
    public TbBossTemplate(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, BossTemplate>(n);
        _dataList = new System.Collections.Generic.List<BossTemplate>(n);
        for(int i = n ; i > 0 ; --i)
        {
            BossTemplate _v;
            _v = global::GameConfig.BossTemplate.DeserializeBossTemplate(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CycleIndex, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, BossTemplate> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<BossTemplate> DataList => _dataList;

    public BossTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BossTemplate Get(int key) => _dataMap[key];
    public BossTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

