
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 卡牌显示模板
/// </summary>
public partial class TbCardTemplate
{
    private readonly System.Collections.Generic.Dictionary<ERace, CardTemplate> _dataMap;
    private readonly System.Collections.Generic.List<CardTemplate> _dataList;
    
    public TbCardTemplate(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<ERace, CardTemplate>(n);
        _dataList = new System.Collections.Generic.List<CardTemplate>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CardTemplate _v;
            _v = global::GameConfig.CardTemplate.DeserializeCardTemplate(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Race, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<ERace, CardTemplate> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CardTemplate> DataList => _dataList;

    public CardTemplate GetOrDefault(ERace key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CardTemplate Get(ERace key) => _dataMap[key];
    public CardTemplate this[ERace key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

