
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 卡牌卖出价格
/// </summary>
public partial class TbCardSellPrice
{
    private readonly System.Collections.Generic.Dictionary<int, CardSellPrice> _dataMap;
    private readonly System.Collections.Generic.List<CardSellPrice> _dataList;
    
    public TbCardSellPrice(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CardSellPrice>(n);
        _dataList = new System.Collections.Generic.List<CardSellPrice>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CardSellPrice _v;
            _v = global::GameConfig.CardSellPrice.DeserializeCardSellPrice(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FaceValue, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CardSellPrice> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CardSellPrice> DataList => _dataList;

    public CardSellPrice GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CardSellPrice Get(int key) => _dataMap[key];
    public CardSellPrice this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

