
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 食客池
/// </summary>
public partial class TbDinerPool
{
    private readonly System.Collections.Generic.Dictionary<int, DinerPool> _dataMap;
    private readonly System.Collections.Generic.List<DinerPool> _dataList;
    
    public TbDinerPool(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DinerPool>(n);
        _dataList = new System.Collections.Generic.List<DinerPool>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DinerPool _v;
            _v = global::GameConfig.DinerPool.DeserializeDinerPool(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DinerPool> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DinerPool> DataList => _dataList;

    public DinerPool GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DinerPool Get(int key) => _dataMap[key];
    public DinerPool this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

