
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 食客模板
/// </summary>
public partial class TbDinerTemplate
{
    private readonly System.Collections.Generic.Dictionary<int, DinerTemplate> _dataMap;
    private readonly System.Collections.Generic.List<DinerTemplate> _dataList;
    
    public TbDinerTemplate(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DinerTemplate>(n);
        _dataList = new System.Collections.Generic.List<DinerTemplate>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DinerTemplate _v;
            _v = global::GameConfig.DinerTemplate.DeserializeDinerTemplate(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DinerTemplate> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DinerTemplate> DataList => _dataList;

    public DinerTemplate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DinerTemplate Get(int key) => _dataMap[key];
    public DinerTemplate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

