
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 情绪路径
/// </summary>
public partial class TbEmotionPath
{
    private readonly System.Collections.Generic.Dictionary<EEmotionPathId, EmotionPath> _dataMap;
    private readonly System.Collections.Generic.List<EmotionPath> _dataList;
    
    public TbEmotionPath(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<EEmotionPathId, EmotionPath>(n);
        _dataList = new System.Collections.Generic.List<EmotionPath>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EmotionPath _v;
            _v = global::GameConfig.EmotionPath.DeserializeEmotionPath(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<EEmotionPathId, EmotionPath> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EmotionPath> DataList => _dataList;

    public EmotionPath GetOrDefault(EEmotionPathId key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EmotionPath Get(EEmotionPathId key) => _dataMap[key];
    public EmotionPath this[EEmotionPathId key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

