
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 设施定义
/// </summary>
public partial class TbFacility
{
    private readonly System.Collections.Generic.Dictionary<int, Facility> _dataMap;
    private readonly System.Collections.Generic.List<Facility> _dataList;
    
    public TbFacility(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Facility>(n);
        _dataList = new System.Collections.Generic.List<Facility>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Facility _v;
            _v = global::GameConfig.Facility.DeserializeFacility(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Facility> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Facility> DataList => _dataList;

    public Facility GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Facility Get(int key) => _dataMap[key];
    public Facility this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

