
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 口味到面值映射表
/// </summary>
public partial class TbFlavorToFaceValue
{
    private readonly System.Collections.Generic.Dictionary<int, FlavorToFaceValue> _dataMap;
    private readonly System.Collections.Generic.List<FlavorToFaceValue> _dataList;
    
    public TbFlavorToFaceValue(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, FlavorToFaceValue>(n);
        _dataList = new System.Collections.Generic.List<FlavorToFaceValue>(n);
        for(int i = n ; i > 0 ; --i)
        {
            FlavorToFaceValue _v;
            _v = global::GameConfig.FlavorToFaceValue.DeserializeFlavorToFaceValue(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Flavor, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, FlavorToFaceValue> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<FlavorToFaceValue> DataList => _dataList;

    public FlavorToFaceValue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FlavorToFaceValue Get(int key) => _dataMap[key];
    public FlavorToFaceValue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

