
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 全局常量（单例）
/// </summary>
public partial class TbGlobalConst
{

     private readonly GlobalConst _data;

     public GlobalConst Data => _data;

    public TbGlobalConst(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.GlobalConst.DeserializeGlobalConst(_buf);
    }


    /// <summary>
    /// 伪装型方差倍率
    /// </summary>
     public float DisguiseMultiplier => _data.DisguiseMultiplier;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

