
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 种族定义表
/// </summary>
public partial class TbRace
{
    private readonly System.Collections.Generic.Dictionary<int, Race> _dataMap;
    private readonly System.Collections.Generic.List<Race> _dataList;
    
    public TbRace(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Race>(n);
        _dataList = new System.Collections.Generic.List<Race>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Race _v;
            _v = global::GameConfig.Race.DeserializeRace(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Race> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Race> DataList => _dataList;

    public Race GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Race Get(int key) => _dataMap[key];
    public Race this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

