
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 餐厅进度配置
/// </summary>
public partial class TbRestaurantProgress
{
    private readonly System.Collections.Generic.Dictionary<int, RestaurantProgress> _dataMap;
    private readonly System.Collections.Generic.List<RestaurantProgress> _dataList;
    
    public TbRestaurantProgress(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RestaurantProgress>(n);
        _dataList = new System.Collections.Generic.List<RestaurantProgress>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RestaurantProgress _v;
            _v = global::GameConfig.RestaurantProgress.DeserializeRestaurantProgress(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Day, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, RestaurantProgress> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RestaurantProgress> DataList => _dataList;

    public RestaurantProgress GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RestaurantProgress Get(int key) => _dataMap[key];
    public RestaurantProgress this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

