
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 遗物定义(预留)
/// </summary>
public partial class TbRelic
{
    private readonly System.Collections.Generic.Dictionary<int, Relic> _dataMap;
    private readonly System.Collections.Generic.List<Relic> _dataList;
    
    public TbRelic(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Relic>(n);
        _dataList = new System.Collections.Generic.List<Relic>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Relic _v;
            _v = global::GameConfig.Relic.DeserializeRelic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Relic> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Relic> DataList => _dataList;

    public Relic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Relic Get(int key) => _dataMap[key];
    public Relic this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

