
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 座位类型
/// </summary>
public partial class TbSeatType
{
    private readonly System.Collections.Generic.Dictionary<int, SeatType> _dataMap;
    private readonly System.Collections.Generic.List<SeatType> _dataList;
    
    public TbSeatType(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SeatType>(n);
        _dataList = new System.Collections.Generic.List<SeatType>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SeatType _v;
            _v = global::GameConfig.SeatType.DeserializeSeatType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SeatType> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SeatType> DataList => _dataList;

    public SeatType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SeatType Get(int key) => _dataMap[key];
    public SeatType this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

