
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 商店配置（单例）
/// </summary>
public partial class TbShopConfig
{

     private readonly ShopConfig _data;

     public ShopConfig Data => _data;

    public TbShopConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.ShopConfig.DeserializeShopConfig(_buf);
    }


    /// <summary>
    /// 商店基础展示数
    /// </summary>
     public int BaseShopDisplay => _data.BaseShopDisplay;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

