
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 起始手牌配置（单例）
/// </summary>
public partial class TbStartingCardConfig
{

     private readonly StartingCardConfig _data;

     public StartingCardConfig Data => _data;

    public TbStartingCardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.StartingCardConfig.DeserializeStartingCardConfig(_buf);
    }


    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

