
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 每日关卡配置
/// </summary>
public partial class TbStage
{
    private readonly System.Collections.Generic.Dictionary<int, Stage> _dataMap;
    private readonly System.Collections.Generic.List<Stage> _dataList;
    
    public TbStage(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Stage>(n);
        _dataList = new System.Collections.Generic.List<Stage>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Stage _v;
            _v = global::GameConfig.Stage.DeserializeStage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Day, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Stage> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Stage> DataList => _dataList;

    public Stage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Stage Get(int key) => _dataMap[key];
    public Stage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

