
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 食客特质
/// </summary>
public partial class TbTrait
{
    private readonly System.Collections.Generic.Dictionary<int, Trait> _dataMap;
    private readonly System.Collections.Generic.List<Trait> _dataList;
    
    public TbTrait(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Trait>(n);
        _dataList = new System.Collections.Generic.List<Trait>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Trait _v;
            _v = global::GameConfig.Trait.DeserializeTrait(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Trait> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Trait> DataList => _dataList;

    public Trait GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Trait Get(int key) => _dataMap[key];
    public Trait this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

